#include "Color.h"

BEGIN_OGS_NAMESPACE
IMPLEMENT_CLASS_BASE(Color)

BEGIN_REFLEX_CLASS_FIELD(Color)
REFLEX_FIELD(float, r)
REFLEX_FIELD(float, g)
REFLEX_FIELD(float, b)
REFLEX_FIELD(float, a)
END_REFLEX_CLASS_FIELD()

END_OGS_NAMESPACE