#include "Vector3.h"

BEGIN_OGS_NAMESPACE

IMPLEMENT_CLASS_BASE(Vector3)

BEGIN_REFLEX_CLASS_FIELD(Vector3)
REFLEX_FIELD(float, x)
REFLEX_FIELD(float, y)
REFLEX_FIELD(float, z)
END_REFLEX_CLASS_FIELD()

END_OGS_NAMESPACE