#include "Vector4.h"

BEGIN_OGS_NAMESPACE
IMPLEMENT_CLASS_BASE(Vector4)

BEGIN_REFLEX_CLASS_FIELD(Vector4)
REFLEX_FIELD(float, x)
REFLEX_FIELD(float, y)
REFLEX_FIELD(float, z)
REFLEX_FIELD(float, w)
END_REFLEX_CLASS_FIELD()

END_OGS_NAMESPACE