#include "gfx_base_define.h"

BEGIN_OGS_GFX_NAMESPACE

static const FormatInfo formatInfos[(int)Format::COUNT] = {
	{ "UNKNOWN", 0, 0, FormatType::NONE, false, false, false, false},

	{ "A8", 1, 1, FormatType::UNORM, true, false, false, false},
	{ "L8", 1, 1, FormatType::UNORM, false, false, false, false},
	{ "LA8", 1, 2, FormatType::UNORM, true, false, false, false},

	{ "R8", 1, 1, FormatType::UNORM, false, false, false, false},
	{ "R8SN", 1, 1, FormatType::SNORM, false, false, false, false},
	{ "R8UI", 1, 1, FormatType::UINT, false, false, false, false},
	{ "R8I", 1, 1, FormatType::INT, false, false, false, false},
	{ "R16F", 2, 1, FormatType::FLOAT, false, false, false, false},
	{ "R16UI", 2, 1, FormatType::UINT, false, false, false, false},
	{ "R16I", 2, 1, FormatType::INT, false, false, false, false},
	{ "R32F", 4, 1, FormatType::FLOAT, false, false, false, false},
	{ "R32UI", 4, 1, FormatType::UINT, false, false, false, false},
	{ "R32I", 4, 1, FormatType::INT, false, false, false, false},

	{ "RG8", 2, 2, FormatType::UNORM, false, false, false, false},
	{ "RG8SN", 2, 2, FormatType::SNORM, false, false, false, false},
	{ "RG8UI", 2, 2, FormatType::UINT, false, false, false, false},
	{ "RG8I", 2, 2, FormatType::INT, false, false, false, false},
	{ "RG16F", 4, 2, FormatType::FLOAT, false, false, false, false},
	{ "RG16UI", 4, 2, FormatType::UINT, false, false, false, false},
	{ "RG16I", 4, 2, FormatType::INT, false, false, false, false},
	{ "RG32F", 8, 2, FormatType::FLOAT, false, false, false, false},
	{ "RG32UI", 8, 2, FormatType::UINT, false, false, false, false},
	{ "RG32I", 8, 2, FormatType::INT, false, false, false, false},

	{ "RGB8", 3, 3, FormatType::UNORM, false, false, false, false},
	{ "SRGB8", 3, 3, FormatType::UNORM, false, false, false, false},
	{ "RGB8SN", 3, 3, FormatType::SNORM, false, false, false, false},
	{ "RGB8UI", 3, 3, FormatType::UINT, false, false, false, false},
	{ "RGB8I", 3, 3, FormatType::INT, false, false, false, false},
	{ "RGB16F", 6, 3, FormatType::FLOAT, false, false, false, false},
	{ "RGB16UI", 6, 3, FormatType::UINT, false, false, false, false},
	{ "RGB16I", 6, 3, FormatType::INT, false, false, false, false},
	{ "RGB32F", 12, 3, FormatType::FLOAT, false, false, false, false},
	{ "RGB32UI", 12, 3, FormatType::UINT, false, false, false, false},
	{ "RGB32I", 12, 3, FormatType::INT, false, false, false, false},

	{ "RGBA8", 4, 4, FormatType::UNORM, true, false, false, false},
	{ "BGRA8", 4, 4, FormatType::UNORM, true, false, false, false},
	{ "SRGB8_A8", 4, 4, FormatType::UNORM, true, false, false, false},
	{ "RGBA8SN", 4, 4, FormatType::SNORM, true, false, false, false},
	{ "RGBA8UI", 4, 4, FormatType::UINT, true, false, false, false},
	{ "RGBA8I", 4, 4, FormatType::INT, true, false, false, false},
	{ "RGBA16F", 8, 4, FormatType::FLOAT, true, false, false, false},
	{ "RGBA16UI", 8, 4, FormatType::UINT, true, false, false, false},
	{ "RGBA16I", 8, 4, FormatType::INT, true, false, false, false},
	{ "RGBA32F", 16, 4, FormatType::FLOAT, true, false, false, false},
	{ "RGBA32UI", 16, 4, FormatType::UINT, true, false, false, false},
	{ "RGBA32I", 16, 4, FormatType::INT, true, false, false, false},

	{ "R5G6B5", 2, 3, FormatType::UNORM, false, false, false, false},
	{ "R11G11B10F", 4, 3, FormatType::FLOAT, false, false, false, false},
	{ "RGB5A1", 2, 4, FormatType::UNORM, true, false, false, false},
	{ "RGBA4", 2, 4, FormatType::UNORM, true, false, false, false},
	{ "RGB10A2", 2, 4, FormatType::UNORM, true, false, false, false},
	{ "RGB10A2UI", 2, 4, FormatType::UINT, true, false, false, false},
	{ "RGB9E5", 2, 4, FormatType::FLOAT, true, false, false, false},

	{ "DEPTH", 4, 1, FormatType::FLOAT, false, true, false, false},
	{ "DEPTH_STENCIL", 5, 2, FormatType::FLOAT, false, true, true, false},

	{ "BC1", 1, 3, FormatType::UNORM, false, false, false, true},
	{ "BC1_ALPHA", 1, 4, FormatType::UNORM, true, false, false, true},
	{ "BC1_SRGB", 1, 3, FormatType::UNORM, false, false, false, true},
	{ "BC1_SRGB_ALPHA", 1, 4, FormatType::UNORM, true, false, false, true},
	{ "BC2", 1, 4, FormatType::UNORM, true, false, false, true},
	{ "BC2_SRGB", 1, 4, FormatType::UNORM, true, false, false, true},
	{ "BC3", 1, 4, FormatType::UNORM, true, false, false, true},
	{ "BC3_SRGB", 1, 4, FormatType::UNORM, true, false, false, true},
	{ "BC4", 1, 1, FormatType::UNORM, false, false, false, true},
	{ "BC4_SNORM", 1, 1, FormatType::SNORM, false, false, false, true},
	{ "BC5", 1, 2, FormatType::UNORM, false, false, false, true},
	{ "BC5_SNORM", 1, 2, FormatType::SNORM, false, false, false, true},
	{ "BC6H_UF16", 1, 3, FormatType::UFLOAT, false, false, false, true},
	{ "BC6H_SF16", 1, 3, FormatType::FLOAT, false, false, false, true},
	{ "BC7", 1, 4, FormatType::UNORM, true, false, false, true},
	{ "BC7_SRGB", 1, 4, FormatType::UNORM, true, false, false, true},

	{ "ETC_RGB8", 1, 3, FormatType::UNORM, false, false, false, true},
	{ "ETC2_RGB8", 1, 3, FormatType::UNORM, false, false, false, true},
	{ "ETC2_SRGB8", 1, 3, FormatType::UNORM, false, false, false, true},
	{ "ETC2_RGB8_A1", 1, 4, FormatType::UNORM, true, false, false, true},
	{ "ETC2_SRGB8_A1", 1, 4, FormatType::UNORM, true, false, false, true},
	{ "ETC2_RGBA8", 2, 4, FormatType::UNORM, true, false, false, true},
	{ "ETC2_SRGB8_A8", 2, 4, FormatType::UNORM, true, false, false, true},
	{ "EAC_R11", 1, 1, FormatType::UNORM, false, false, false, true},
	{ "EAC_R11SN", 1, 1, FormatType::SNORM, false, false, false, true},
	{ "EAC_RG11", 2, 2, FormatType::UNORM, false, false, false, true},
	{ "EAC_RG11SN", 2, 2, FormatType::SNORM, false, false, false, true},

	{ "PVRTC_RGB2", 2, 3, FormatType::UNORM, false, false, false, true},
	{ "PVRTC_RGBA2", 2, 4, FormatType::UNORM, true, false, false, true},
	{ "PVRTC_RGB4", 2, 3, FormatType::UNORM, false, false, false, true},
	{ "PVRTC_RGBA4", 2, 4, FormatType::UNORM, true, false, false, true},
	{ "PVRTC2_2BPP", 2, 4, FormatType::UNORM, true, false, false, true},
	{ "PVRTC2_4BPP", 2, 4, FormatType::UNORM, true, false, false, true},

	{ "ASTC_RGBA_4x4", 1, 4, FormatType::UNORM, true, false, false, true},
	{ "ASTC_RGBA_5x4", 1, 4, FormatType::UNORM, true, false, false, true},
	{ "ASTC_RGBA_5x5", 1, 4, FormatType::UNORM, true, false, false, true},
	{ "ASTC_RGBA_6x5", 1, 4, FormatType::UNORM, true, false, false, true},
	{ "ASTC_RGBA_6x6", 1, 4, FormatType::UNORM, true, false, false, true},
	{ "ASTC_RGBA_8x5", 1, 4, FormatType::UNORM, true, false, false, true},
	{ "ASTC_RGBA_8x6", 1, 4, FormatType::UNORM, true, false, false, true},
	{ "ASTC_RGBA_8x8", 1, 4, FormatType::UNORM, true, false, false, true},
	{ "ASTC_RGBA_10x5", 1, 4, FormatType::UNORM, true, false, false, true},
	{ "ASTC_RGBA_10x6", 1, 4, FormatType::UNORM, true, false, false, true},
	{ "ASTC_RGBA_10x8", 1, 4, FormatType::UNORM, true, false, false, true},
	{ "ASTC_RGBA_10x10", 1, 4, FormatType::UNORM, true, false, false, true},
	{ "ASTC_RGBA_12x10", 1, 4, FormatType::UNORM, true, false, false, true},
	{ "ASTC_RGBA_12x12", 1, 4, FormatType::UNORM, true, false, false, true},

	{ "ASTC_SRGBA_4x4", 1, 4, FormatType::UNORM, true, false, false, true},
	{ "ASTC_SRGBA_5x4", 1, 4, FormatType::UNORM, true, false, false, true},
	{ "ASTC_SRGBA_5x5", 1, 4, FormatType::UNORM, true, false, false, true},
	{ "ASTC_SRGBA_6x5", 1, 4, FormatType::UNORM, true, false, false, true},
	{ "ASTC_SRGBA_6x6", 1, 4, FormatType::UNORM, true, false, false, true},
	{ "ASTC_SRGBA_8x5", 1, 4, FormatType::UNORM, true, false, false, true},
	{ "ASTC_SRGBA_8x6", 1, 4, FormatType::UNORM, true, false, false, true},
	{ "ASTC_SRGBA_8x8", 1, 4, FormatType::UNORM, true, false, false, true},
	{ "ASTC_SRGBA_10x5", 1, 4, FormatType::UNORM, true, false, false, true},
	{ "ASTC_SRGBA_10x6", 1, 4, FormatType::UNORM, true, false, false, true},
	{ "ASTC_SRGBA_10x8", 1, 4, FormatType::UNORM, true, false, false, true},
	{ "ASTC_SRGBA_10x10", 1, 4, FormatType::UNORM, true, false, false, true},
	{ "ASTC_SRGBA_12x10", 1, 4, FormatType::UNORM, true, false, false, true},
	{ "ASTC_SRGBA_12x12", 1, 4, FormatType::UNORM, true, false, false, true},
};
const FormatInfo& getFormatInfo(Format type)
{
	return formatInfos[(int)type];
}

static const char* s_attribteName[(int)AttributeName::COUNT] = {
	"a_position",
	"a_normal",
	"a_tangent",
	"a_bitangent",
	"a_weights",
	"a_joints",
	"a_color",
	"a_color1",
	"a_color2",
	"a_texCoord",
	"a_texCoord1",
	"a_texCoord2",
	"a_texCoord3",
	"a_texCoord4",
	"a_texCoord5",
	"a_texCoord6",
	"a_texCoord7",
	"a_texCoord8",
	"a_batch_id",
	"a_batch_uv",
};

const char* getAttributeName(AttributeName name)
{
	return s_attribteName[(int)name];
}
END_OGS_GFX_NAMESPACE